server:
  port: 8080

elasticport: 9200
elastichost: http://localhost
elasticPersonIndex: person
elasticPersonType: employee
elasticAptitudeIndex: aptitude
elasticAptitudeType: aptitude
elasticSurveyIndex: survey
elasticSurveyType: survey
elasticAdministratorIndex: user
elasticAdministratorType: administrator
